config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bets do
    resources :validities, only: [:create]
    resources :feelings, only: [:create]
    resources :track_bets, only: [:create, :destroy]
  end
  root to: "bets#index"
  get :dashboard, to: "pages#dashboard"
  get :rules, to: "pages#rules"
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bet.rb
class Bet < ApplicationRecord
  include ::ScoreCompute::BetFeelingScore
  include ::ScoreCompute::BetValidityScore
  include PgSearch::Model

  pg_search_scope :search_by_title, against: [:title], associated_against: {tags: :name}

  STATI = [
    UNVALIDATED = "UNVALIDATED",
    INVALID = "INVALID",
    VALID = "VALID",
    DATE_PASSED = "DATE_PASSED",
    HAPPENED = "HAPPENED",
    NOT_HAPPENED = "NOT_HAPPENED",
  ]

  STATI_DISPLAY = [
    ["unvalidated yet", UNVALIDATED],
    ["invalid", INVALID],
    ["valid", VALID],
    ["date passed", DATE_PASSED],
    ["event has happened", HAPPENED],
    ["event hasn't happened", NOT_HAPPENED],
  ]

  BET_FEELING_VOTED = [
    BET_FEELING_VOTED_NOT_YET = "BET_FEELING_VOTED_NOT_YET",
    BET_FEELING_VOTED_FOR = "BET_FEELING_VOTED_FOR",
    BET_FEELING_VOTED_AGAINST = "BET_FEELING_VOTED_AGAINST"
  ]

  BET_VALIDITY_VOTED = [
    BET_VALIDITY_VOTED_NOT_YET = "BET_VALIDITY_VOTED_NOT_YET",
    BET_VALIDITY_VOTED_AGAINST = "BET_VALIDITY_VOTED_AGAINST",
    BET_VALIDITY_VOTED_FOR = "BET_VALIDITY_VOTED_FOR"
  ]

  VOTES_FILTER = [
    BET_FEELING_VOTED,
    BET_VALIDITY_VOTED,
    BETS_TRACKED = "BETS_TRACKED"
  ].flatten

  VOTES_FILTER_DISPLAY = [
    ["bets not voted for yet", BET_FEELING_VOTED_NOT_YET],
    ["bets you've voted for", BET_FEELING_VOTED_FOR],
    ["bets you've voted against", BET_FEELING_VOTED_AGAINST],
    ["bets not you haven't validated yet", BET_VALIDITY_VOTED_NOT_YET],
    ["bets you've unvalidated", BET_VALIDITY_VOTED_AGAINST],
    ["bets you've validated", BET_VALIDITY_VOTED_FOR],
    ["bets you're tracking", BETS_TRACKED],
  ]

  SORT_FILTER = [
    CREATED_AT_ASC = "CREATED_AT_ASC",
    CREATED_AT_DESC = "CREATED_AT_DESC",
    NUMBER_VALIDITIES_ASC = "NUMBER_VALIDITIES_ASC",
    NUMBER_VALIDITIES_DESC = "NUMBER_VALIDITIES_DESC",
    NUMBER_FEELINGS_ASC = "NUMBER_FEELINGS_ASC",
    NUMBER_FEELINGS_DESC = "NUMBER_FEELINGS_DESC"
  ]
  SORT_FILTER_DISPLAY = [
    ["descending by creation", CREATED_AT_DESC],
    ["ascending by creation", CREATED_AT_ASC],
    ["most valid to least valid", NUMBER_VALIDITIES_ASC],
    ["least valid to most valid", NUMBER_VALIDITIES_DESC],
    ["most amount of bets to least amount", NUMBER_FEELINGS_ASC],
    ["least amount of bets to most amount", NUMBER_FEELINGS_DESC]
  ]

  belongs_to :user
  has_many :validities, dependent: :nullify
  has_many :feelings, dependent: :nullify
  has_many :bet_tags
  has_many :tags, through: :bet_tags

  validates :title, presence: true, uniqueness: true
  validates :status, presence: true, inclusion: {in: STATI}
  validates :end_date, presence: true
  validates :end_votes_date, presence: true
  validate :total_score_allows
  validate :end_votes_date_after_end_date

  after_update :process_feelings, if: :saved_change_to_status?
  after_create :update_score

  attr_accessor :user_voted_for, :points

  after_initialize :init

  def init
    points = {}
    points ||= points
    self.status ||= UNVALIDATED
  end

  def validity_voted_for(user)
    validities.detect { |validity| validity.user_id == user.id }
  end

  def feeling_voted_for(user)
    feelings.detect { |feeling| feeling.user_id == user.id }
  end

  def feelings_average
    if feelings.size > 0
      feelings.sum { |feeling| feeling.weight_certainty }.div(feelings.size)
    else
      0
    end
  end

  def process_feelings
    ScoreFeelingsJob.perform_later(id) if [HAPPENED, NOT_HAPPENED].include?(status)
  end

  def passed_validation
    self.status != UNVALIDATED
  end

  def validated
    [VALID, DATE_PASSED, HAPPENED, NOT_HAPPENED].include?(status)
  end

  def self.list_bets(params, user)
    bets = includes(:user, :tags, validities: [:user], feelings: [:user], user: :tracked_bets).where(nil)
    votes_filter = params.delete(:votes_filter) if params[:votes_filter].present?
    return user.tracked_bets if votes_filter&.include? Bet::BETS_TRACKED
    votes_search = params.delete(:search) if params[:search].present?
    votes_sort = params.delete(:sort_by) if params[:sort_by].present?
    params.each do |key, value|
      bets = bets.where(key => value) if value.present?
    end
    bets = vote_filter(votes_filter, bets, user) if votes_filter
    bets = bets.search_by_title(votes_search) if votes_search
    bets = bets.sorting_by(votes_sort, bets) if votes_sort
    bets
  end

  private

  def self.sorting_by(votes_sort, bets)
    case votes_sort
    when CREATED_AT_DESC
      bets.order(created_at: :asc)
    when CREATED_AT_DESC
      bets.order(created_at: :desc)
    when NUMBER_FEELINGS_ASC
      bets.order("feelings_count asc")
    when NUMBER_FEELINGS_DESC
      bets.order("feelings_count desc")
    when NUMBER_VALIDITIES_ASC
      bets.order("validities_count asc")
    when NUMBER_VALIDITIES_DESC
      bets.order("validities_count desc")
    else
      bets
    end
  end

  def self.vote_filter(votes_filter, bets, user)
    votes_filter.delete("")
    if votes_filter.include? Bet::BET_VALIDITY_VOTED_NOT_YET
      bets = bets.where.not(id: user.validities.map(&:bet_id))
    end
    if votes_filter.include? Bet::BET_VALIDITY_VOTED_FOR
      bets = bets.where(id: user.validities.where(up_vote: true).map(&:bet_id))
    end
    if votes_filter.include? Bet::BET_VALIDITY_VOTED_AGAINST
      bets = bets.where(id: user.validities.where(up_vote: false).map(&:bet_id))
    end

    if votes_filter.include? Bet::BET_FEELING_VOTED_NOT_YET
      bets = bets.where.not(id: user.feelings.map(&:bet_id))
    end
    if votes_filter.include? Bet::BET_FEELING_VOTED_FOR
      bets = bets.where(id: user.feelings.where(up_vote: true).map(&:bet_id))
    end
    if votes_filter.include? Bet::BET_FEELING_VOTED_AGAINST
      bets = bets.where(id: user.feelings.where(up_vote: false).map(&:bet_id))
    end

    bets
  end

  def total_score_allows
    if status == "UNVALIDATED" && user.total_score.points < TotalScore::POINTS_BET_TYPE[:bet]
      errors.add(:user, "Doesnt have enough points ")
    end
  end

  def end_votes_date_after_end_date
    if end_date < end_votes_date
      errors.add(:end_votes_date, "The end date can't be after the event date")
    end
  end

  def update_score
    user.total_score.points -= TotalScore::POINTS_BET_TYPE[:bet]
    user.total_score.save
  end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  include Pagy::Backend
  before_action :authenticate_user!, except: [:index]
  before_action :set_bet, only: [:show, :edit, :update, :destroy]
  before_action :reset_filters, only: :index

  # GET /bets
  # GET /bets.json
  def index
    @bets = Bet.list_bets(@list_params, current_user)
    @pagy, @bets = pagy(@bets, items: 30)
    entries_string = render_to_string(partial: "bets/bets", locals: {bets: @bets})
    pagination_string = view_context.pagy_nav(@pagy)
    respond_to do |format|
      format.html
      format.json {
        render json: {
          entries: entries_string,
          pagination: pagination_string
        }
      }
    end
  end

  # GET /bets/1
  # GET /bets/1.json
  def show
  end

  # GET /bets/new
  def new
    @bet = Bet.new
  end

  # GET /bets/1/edit
  def edit
  end

  # POST /bets
  # POST /bets.json
  def create
    @bet = Bet.new(bet_params)
    @bet.user = current_user
    respond_to do |format|
      if @bet.save
        tags_params[:tag_names].each { |t_name| @bet.tags << Tag.find_or_create_by!(name: t_name) }
        format.html { redirect_to dashboard_path, notice: "Bet was successfully created." }
        format.json { render :show, status: :created, location: @bet }
      else
        format.html { render :new }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bets/1
  # PATCH/PUT /bets/1.json
  def update
    redirect_to bets_path unless @bet.user == current_user
    @bet.update(bet_params)
    card_string = render_to_string(partial: "bets/card.html.erb", locals: {bet: @bet.reload}, formats: :html)
    render json: {inner_html: card_string}, status: 200
  end

  # DELETE /bets/1
  # DELETE /bets/1.json
  def destroy
    @bet.destroy
    respond_to do |format|
      format.html { redirect_to bets_url, notice: "Bet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def reset_filters 
    @list_params = params[:bet_query].present? ? params[:bet_query].deep_dup : {}
    if @list_params[:reset_filter].present?
      @list_params.delete(:status)
      @list_params.delete(:sort_by)
      params[:bet_query][:sort_by] = nil if params.dig(:bet_query, :sort_by)
      params[:bet_query][:status] = nil if params.dig(:bet_query, :status)

      @list_params.delete(:reset_filter)
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_bet
    @bet = Bet.find(params[:id])
  end

  def tags_params
    params.require(:tag).permit(tag_names: [])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bet_params
    params.require(:bet).permit(:title, :status, :end_date, :end_votes_date, :validated, :happened)
  end
end

app/views/bets/_average.html.erb
<div class="text-center"> average: <%= bet.feelings_average %>% </div>
<progress class="mb-2 form-control-range" id="feelings average" value="<%= bet.feelings_average %>" max="100">  </progress>

app/views/bets/_bet.html.erb
  <div class="card w-100 h-100 m-2 h-auto bet-card" data-controller="bets modal-url-binder clipboard"
    data-id="<%= bet.id %>" id="bet-<%= bet.id %>">

    <%= render "bets/card", bet: bet, validity: Validity.new, feeling: Feeling.new %>
    <%= render layout: "shared/modal_partial", locals: { modal_id: "modal_#{bet.id}" } do %>
      <%= render "bets/card", bet: bet, validity: Validity.new, feeling: Feeling.new %>

    <% end %>
  </div>

app/views/bets/_bets.html.erb
<% bets.each do |bet| %>
<!-- -->
  <%= render 'bets/bet', bet: bet %>
<% end %>

app/views/bets/_card.html.erb
  <div class="card-body d-flex flex-column justify-content-between">
    <p class="card-title">
      <%= bet.title %>
    </p>
    <p>
      <small>End date:</small>
      <%= bet.end_date %>
    </p>
    <p>
      <small>End votes date:</small>
      <%= bet.end_votes_date %>
    </p>
    <% bet.tags.each do |tag| %>
      <span class="badge badge-pill badge-secondary m-1"><%= tag.name %></span>
    <% end %>
  </div>
  <% unless user_signed_in? %>
    <%= link_to "Participate", new_user_session_path, class: "btn btn-primary" %>
  <% end %>

  <% if user_signed_in? && (bet.status == Bet::UNVALIDATED && !bet.validity_voted_for(current_user)) %>
    <%= render "bets/unvalidated_unvoted", bet: bet, validity: validity, cached: true%>
  <% elsif user_signed_in? &&  (bet.status == Bet::UNVALIDATED || bet.status == Bet::INVALID )%>
    <%= render "bets/unvalidated_voted", bet: bet, cached: true %>
  <% elsif user_signed_in? && ( bet.status == Bet::VALID && !bet.feeling_voted_for(current_user) ) %>
    <%= render "bets/validated_unvoted", bet: bet, feeling: feeling, cached: true %>
  <% elsif user_signed_in? && bet.feeling_voted_for(current_user) && bet.status != Bet::DATE_PASSED   %>
    <%= render "bets/validated_voted", bet: bet, cached: true %>
  <% end %>
  <% if bet.status == Bet::DATE_PASSED %>
    <%= render "bets/date_passed", bet: bet, cached: true %>
  <% elsif user_signed_in? && bet.feeling_voted_for(current_user)  %>
    <%= render "bets/happened_or_not", bet: bet, cached: true %>
  <% end %>
<% if Rails.env.development? %>
 <strong> <%= bet.status %> </strong>
<% end %>

<% if user_signed_in? && @tracked_bets.detect{|b| b == bet} %>
  <button data-action="click->bets#submit_track" class="btn btn-sm btn-danger"> Untrack it </button>
<% elsif user_signed_in? %>
  <button data-action="click->bets#submit_track" class="btn btn-sm btn-light"> Track it </button>
<% end %>

<div class="pull-right">
  <i class="fas fa-share-alt float-right m-1 text-muted small"  data-toggle="modal" data-target="#modal_<%= bet.id %>">
    share
  </i>
</div>

app/views/bets/_date_passed.html.erb
<div class="d-flex flex-column justify-content-around">
  <%= render "bets/average", bet: bet%>

  <% if user_signed_in? && current_user == bet.user %>
    <%#= simple_form_for bet do |f| %>
      <%#= f.input :status, input_html: { value:  Bet::HAPPENED }, as: :hidden %>
      <%#= f.button :submit, "HAPPENED",class: "btn btn-light btn-sm" %>
    <%# end %>
    <%#= simple_form_for bet do |f| %>
      <%#= f.input :status, input_html: { value:  Bet::NOT_HAPPENED }, as: :hidden %>
      <%#= f.button :submit, "DID NOT HAPPENED",class: "btn btn-light btn-sm" %>
    <%# end %>
  <div class="d-flex justify-content-around p-2"">
    <button class="btn btn-sm btn-light" data-action="click->bets#submit_happening" data-happening="<%= Bet::HAPPENED %>"> Happened </button>
    <button class="btn btn-sm btn-light" data-action="click->bets#submit_happening" data-happening="<%= Bet::NOT_HAPPENED %>"> Didn't Happened </button>
  </div>
  <% else %>
    <span class="text-center"> Waiting for the creator to say wither it happened </span>
  <% end %>

</div>

app/views/bets/_form.html.erb
<%= simple_form_for(bet) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs" data-controller="new-bet">
    <%= f.input :title %>
    <%= f.input :end_date, as: :string, input_html: { data: { target: "new-bet.dateEvent"}} %>
    <%= f.input :end_votes_date, as: :string, input_html: { data: { target: "new-bet.dateVote"}} %>
    <div class="form-group select optional bet_tag_list">
      <%= label_tag "tag[tag_names]", "Add Tags" %>
      <%= select_tag "tag[tag_names]", options_from_collection_for_select(ActsAsTaggableOn::Tag.all.map{|t| [t.name,t.name] },
      :first, :last), multiple: true,
      class: 'select2 form-control select optional' %>
    </div>
    <%#= f.input :tag_list, collection: ActsAsTaggableOn::Tag.all.map(&:name), input_html: {class: "select2"}, multiple: true%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bets/_happened_or_not.html.erb
HAPPENED OR NOT TO DO !!!

app/views/bets/_unvalidated_unvoted.html.erb
<% unless validity.errors.messages.empty? %>
 <div class="d-flex justify-content-center">
  <span class="text-center alert alert-warning alert-dismissible ">
    <%= validity.errors.messages.to_a.flatten.join(" ") %>
  </span>
</div>
<% end %>
<div class="d-flex justify-content-around p-2">
  <span class="btn w-50 btn-light" data-action="click->bets#submit_validity" data-valid="true"> Valid Prognostic </span>
  <span class="btn w-50 btn-light" data-action="click->bets#submit_validity" data-valid="false"> not really valid </span>
</div>

app/views/bets/_unvalidated_voted.html.erb
<div class="d-flex justify-content-around p-2">
  <button class="btn btn-sm <%= bet.validity_voted_for(current_user).up_vote ? 'btn-primary' : 'btn-light' %>" disabled > Makes Sense - <%= bet.validities.count{|v| v.up_vote}  %> </button>
  <button class="btn btn-sm <%= !bet.validity_voted_for(current_user).up_vote ? 'btn-primary' : 'btn-light' %>" disabled > Not Valid - <%= bet.validities.count{|v| !v.up_vote} %> </button>

</div>

<%#
    bubble_series = []
    array_a = bet.validities.where(up_vote: true).group_by_day(:created_at).count.map(&:to_a)
    array_b = bet.validities.where(up_vote: false).group_by_day(:created_at).count.map(&:to_a)
    bubble_series << { name: "Voted For", data: array_a.map{|sub_array| [sub_array[0], 1, sub_array[1]]} }
   bubble_series <<  { name: "Voted Agains", data: array_b.map{|sub_array| [sub_array[0], -1, sub_array[1]] } }
 %>
<%#= bubble_chart(bubble_series, data_labels: true) %>

app/views/bets/_validated_unvoted.html.erb
<% unless feeling.errors.messages.empty? %>
 <div class="d-flex justify-content-center">
  <span class="text-center alert alert-warning alert-dismissible ">
    <%= feeling.errors.messages.to_a.flatten.join(" ") %>
  </span>
</div>
<% end %>
<div class="text-center" id="feeling-bet-<%= bet.id %>" data-target="bets.feeling">50% sure</div>
<div class="d-flex flex-column justify-content-around p-2">
    <input class="mb-2" type="range" id="vol" name="vol" data-action="change->bets#change_feeling" min="0" max="100" value="50">
    <button class="btn  btn-light" disabled data-target="bets.btnFeeling" data-action="click->bets#submit_feeling" data-valid="false"> ready </button>

</div>

app/views/bets/edit.html.erb
<h1>Editing Bet</h1>

<%= render 'form', bet: @bet %>

<%= link_to 'Show', @bet %> |
<%= link_to 'Back', bets_path %>

app/views/bets/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container" data-controller="infinite-scroll" data-action="scroll@window->infinite-scroll#scroll" >
  <div class="text-center">
    <h1>Bets</h1>
    <small> here is the future we see </small>
  </div>
  <div>
    <%= simple_form_for :bet_query, url: bets_path, method: 'GET' do |f| %>
        <%= f.input :search, input_html: {  data: { controller: "auto-send" , action: "auto-send#send"}, value: params.dig(:bet_query, :search) } %>
        <div class="d-flex justify-content-around">
          <div class="form-group" >
            <%= f.input :reset_filter, label: "", required: false, as: :radio_buttons, collection: ['reset'],  input_html: {  data: { controller: "auto-send" , action: "auto-send#send"}, class: 'tag-selector' },
                  item_wrapper_class: 'tag-item' %>
          </div>
          <div class="form-group" >
            <%= f.input :status, label: "", required: false, as: :radio_buttons, collection: Bet::STATI_DISPLAY,  input_html: {  data: { controller: "auto-send" , action: "auto-send#send"}, class: 'tag-selector' }, checked: params.dig(:bet_query, :status),
                  item_wrapper_class: 'tag-item' %>
          </div>
          <div class="form-group" >
            <%= f.input :sort_by, label: "", required: false, as: :radio_buttons, collection: Bet::SORT_FILTER_DISPLAY,  input_html: {  data: { controller: "auto-send" , action: "auto-send#send"}, class: 'tag-selector' }, checked: params.dig(:bet_query, :sort_by),
                  item_wrapper_class: 'tag-item' %>
         </div>

        <% if current_user %>
          <%= f.input :votes_filter, collection: Bet::VOTES_FILTER_DISPLAY, label_method: :first, input_method: :last, input_html: {  data: { controller: "auto-send" , action: "auto-send#send"}, class: "form-check-input check_boxes optional tag-selector tag-selector" }, checked: params.dig(:bet_query, :votes_filter), as: :check_boxes, include_blank: false, label: "", required: false %>
          <!--  <fieldset class="form-group check_boxes optional " >
            <%# Bet::VOTES_FILTER_DISPLAY.each do |choice| %>
              <div class="tag-item">
                <%#= check_box_tag("bet_query[votes_filter][#{choice.last}]", choice.last, params[:bet_query] && params[:bet_query][:votes_filter] && params[:bet_query][:votes_filter].values.include?(choice.last), {  data: { controller: "auto-send" , action: "auto-send#send"}, class: "form-check-input check_boxes optional tag-selector tag-selector" }) %>
                <%#= label_tag("bet_query[votes_filter][#{choice}]", choice.first, class: "form-check-label collection_check_boxes") %>
              </div>
            <%# end %>
            <%#= f.input :votes_filter, label: "", required: false, as: :check_boxes, collection: Bet::VOTES_FILTER.map{|b| [b, b]},  input_html: {  data: { controller: "auto-send" , action: "auto-send#send"} } %>
          </fieldset> -->
        <% end %>
      </div>
    <% end %>
</div>
  <div class="row row-cols-lg-6 row-cols-md-4 row-cols-sm-12 justify-content-center" data-target="infinite-scroll.entries">
    <%= render "bets/bets", bets: @bets %>
  </div>
  <div data-target="infinite-scroll.pagination" class="sr-only">
    <%== pagy_nav(@pagy) %>
  </div>
</div>

app/views/bets/new.html.erb
<div class="container">
  <h1>New Bet</h1>
  <p><small>
    It will cost you 4 points to create a bet.
  </small></p>
  <%= render 'form', bet: @bet %>
</div>
<%= link_to 'Back', bets_path %>

app/views/bets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bet.title %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bet.status %>
</p>

<p>
  <strong>End date:</strong>
  <%= @bet.end_date %>
</p>

<p>
  <strong>End votes date:</strong>
  <%= @bet.end_votes_date %>
</p>

<%= link_to 'Edit', edit_bet_path(@bet) %> |
<%= link_to 'Back', bets_path %>