config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bets do
    resources :validities, only: [:create]
    resources :feelings, only: [:create]
    resources :track_bets, only: [:create, :destroy]
  end
  root to: "bets#index"
  get :dashboard, to: "pages#dashboard"
  get :rules, to: "pages#rules"
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_modal_partial.html.erb
<div class="modal fade" id="<%= modal_id %>" tabindex="-1" aria-labelledby="exampleModalLabel"
  data-backdrop="static"
  aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="pull-right">
        <i class="fas fa-times float-right m-1" data-dismiss="modal"></i>
      </div>
      <div class="modal-body">
        <%= yield %>
      </div>
      <div class="modal-footer">
        <div>
          url: <input data-target="modal-url-binder.source" type="text" value="1234" readonly>
          <button class="btn btn-light" data-action="modal-url-binder#copy">Copy</button>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="navbar-cable" <%= "data-total-score-id=#{current_user&.total_score.id}" if current_user %> >
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if current_user %>
    <span class="nav-item">
      points: <%= current_user.total_score.points %>
    </span>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if params[:action] == 'rules' %>">
          <%= link_to 'Rules', rules_path, class: "nav-link" %>
      </li>
      <% if current_user %>
        <li class="nav-item <%= 'active' if params[:action] == 'new' %>">
          <%= link_to 'New Bet', new_bet_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if params[:action] == 'dashboard' %> ">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
 <!--        <li class="nav-item dropdown">
          <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%#= link_to "Action", "#", class: "dropdown-item" %>
            <%#= link_to "Another action", "#", class: "dropdown-item" %>
            <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li> -->
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>